import { $, t, esc, shell, icon, action, call, start, value, badge, time, date, empty, openPanel, languageLabel, type Obj } from '../shared/ui';
let sessions:Obj[]=[],filter='all';
shell(t('会话','Sessions'),`<div class="heading"><p class="eyebrow">YOUR CREATIVE SPACE</p><h1>${t('让内容，开始创作。','Make something worth sharing.')}</h1><p class="muted">${t('从一段录音、一份文稿，或一个视频开始。','Start with a recording or a script.')}</p></div><div class="workflow-grid"><button id="new-transcription" class="workflow-card"><span class="workflow-symbol">${icon('text')}</span>${icon('arrow')}<h3>${t('音视频转录','Transcribe')}</h3><p>${t('语音变文字，生成字幕','Turn speech into text & captions')}</p></button><button id="new-dubbing" class="workflow-card voice"><span class="workflow-symbol">${icon('mic')}</span>${icon('arrow')}<h3>${t('AI 配音','Voiceover')}</h3><p>${t('给你的文稿，一个声音','Give your script a voice')}</p></button></div><p class="field-hint native-editing-note">Video edits happen in VoxStudio. Describe your changes in chat to edit the Mac app’s timeline directly.</p><div class="section-heading"><h2>${t('最近会话','Recent sessions')}<span id="count" class="count"></span></h2><button id="refresh" class="icon-button" aria-label="${t('刷新会话','Refresh sessions')}">${icon('refresh')}</button></div><div class="library-controls"><div class="segmented" role="group" aria-label="${t('会话类型','Session type')}"><button data-filter="all" aria-pressed="true">${t('全部','All')}</button><button data-filter="transcription" aria-pressed="false">${t('转录','Transcripts')}</button><button data-filter="dubbing" aria-pressed="false">${t('配音','Voiceovers')}</button></div><label class="search-box">${icon('search')}<input id="search" type="search" placeholder="${t('搜索会话…','Search sessions…')}" aria-label="${t('搜索会话','Search sessions')}"></label></div><div id="sessions" class="session-list"><div class="loading-card"><div class="skeleton"></div><div class="skeleton wide"></div></div></div><p id="navigation-hint" class="field-hint">${t('选择会话后，将在聊天中打开独立的详情面板。','Select a session to open its own detail panel in this chat.')}</p>`);
function render(){
 const query=value('search').trim().toLocaleLowerCase();
 const rows=sessions.filter(s=>(filter==='all'||s.kind===filter)&&String(s.title).toLocaleLowerCase().includes(query));
 $('count').textContent=String(rows.length);
 $('sessions').innerHTML=rows.length?rows.map(s=>`<button class="session-row" data-session="${esc(s.session_id)}"><span class="session-icon ${s.kind==='dubbing'?'voice':''}">${icon(s.kind==='dubbing'?'mic':'text')}</span><span><span class="session-name">${esc(s.title||t('未命名会话','Untitled session'))}</span><span class="session-meta"><span>${t(s.kind==='dubbing'?'配音':'转录',s.kind==='dubbing'?'Voiceover':'Transcript')}</span>${s.duration?`<span>${time(s.duration)}</span>`:''}${s.language?`<span>${esc(languageLabel(s.language))}</span>`:''}${s.updated_at?`<span>${date(s.updated_at)}</span>`:''}</span></span>${badge(s.status)}${icon('arrow')}</button>`).join(''):empty(query?t('没有匹配的会话','No matching sessions'):t('从第一个作品开始','Your first session starts here'),query?t('试试其他名称，或清空搜索。','Try another name or clear the search.'):t('上方选择转录或配音，完成的内容会出现在这里。','Choose Transcribe or Voiceover above. Your work will appear here.'));
 $('sessions').querySelectorAll<HTMLButtonElement>('[data-session]').forEach((button,i)=>{button.id=`session-${i}`;action(button.id,()=>openPanel('app_session',{session_id:button.dataset.session}))});
}
for(const [id,tool]of [['new-transcription','app_transcription'],['new-dubbing','app_dubbing']])action(id,()=>openPanel(tool));
action('refresh',async()=>{sessions=(await call('voxstudio.sessions')).sessions??[];render()});
$('search').oninput=render;
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-filter]'))b.onclick=()=>{filter=b.dataset.filter!;document.querySelectorAll('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));render()};
start('voxstudio.sessions',data=>{sessions=data.sessions??[];render()});
