import { $, t, esc, shell, icon, action, call, start, value, field, backButton, openPanel, openNativeSession, notice, poll, progress, mountPlayer, clearPlayer, languageLabel, time, languages, context, type Obj } from '../shared/ui';
type Cue={id:number;start_ms:number;end_ms:number;text:string;speaker?:string};
let session:Obj|undefined,track:Obj|undefined,editing=false,dirty=false,stopJob:(()=>void)|undefined,loadingTrack=false;
let player:Awaited<ReturnType<typeof mountPlayer>>|undefined;
let previewGeneration=0;
function resetPreview(){previewGeneration++;player=undefined;const container=$('player');if(container)clearPlayer(container);}
shell(t('会话详情','Session'),`<div class="back-row">${backButton()}</div><div id="detail"><div class="loading-card"><div class="skeleton wide"></div><div class="skeleton"></div></div></div>`);
action('back',()=>{if(dirty)throw new Error(t('请先保存或放弃修改','Save or discard your edits first.'));return openPanel('app_workbench')});
function args(){const selected=value('track')||'source';return {session_id:session!.session_id,scope:selected==='source'?'source':'translation',...(selected==='source'?{}:{language:selected})};}
function operations(){const out:Obj[]=[];for(const row of $('cues').querySelectorAll<HTMLElement>('[data-cue]')){const cue=(track?.cues as Cue[]).find(c=>String(c.id)===row.dataset.cue)!;const text=row.querySelector<HTMLTextAreaElement>('textarea')?.value;if(text!==undefined&&text!==cue.text)out.push({type:'text',cue_id:cue.id,text});const start=row.querySelector<HTMLInputElement>('[data-start]'),end=row.querySelector<HTMLInputElement>('[data-end]');if(start&&end){const a=Math.round(Number(start.value)*1000),b=Math.round(Number(end.value)*1000);if(!Number.isFinite(a)||!Number.isFinite(b)||a<0||b<=a)throw new Error(t('结束时间必须晚于开始时间','End time must be after start time.'));if(a!==cue.start_ms||b!==cue.end_ms)out.push({type:'timing',cue_id:cue.id,start_ms:a,end_ms:b})}}return out;}
function renderCues(){const cues:Cue[]=track?.cues??[];$('cue-count').textContent=`${cues.length} ${t('段','segments')}`;$('cues').innerHTML=cues.length?cues.map(c=>`<div class="cue-row" data-cue="${c.id}"><button class="cue-time" data-seek="${c.start_ms/1000}" aria-label="${t('定位到','Seek to')} ${time(c.start_ms/1000)}">${time(c.start_ms/1000)}</button><div>${c.speaker?`<p class="speaker">${esc(c.speaker)}</p>`:''}${editing?`<textarea aria-label="${t('字幕','Caption')} ${c.id}">${esc(c.text)}</textarea><div class="cue-timing"><label>${t('起始秒','Start (s)')} <input type="number" data-start min="0" step="0.001" value="${c.start_ms/1000}"></label><span>→</span><label>${t('结束秒','End (s)')} <input type="number" data-end min="0" step="0.001" value="${c.end_ms/1000}"></label></div>`:`<p class="cue-copy">${esc(c.text)}</p>`}</div></div>`).join(''):`<p class="muted" style="padding:25px 0">${t('这个轨道暂时没有文字。','This track has no text yet.')}</p>`;
 $('cues').querySelectorAll<HTMLButtonElement>('[data-seek]').forEach((b,i)=>{b.id=`seek-${i}`;action(b.id,async()=>{const at=Number(b.dataset.seek);await preview(at);const cue=cues.find(c=>c.start_ms/1000===at);await context({...args(),start_ms:cue?.start_ms,end_ms:cue?.end_ms,text:cue?.text.slice(0,2500)})})});
 $('cues').oninput=()=>{dirty=true;$('save-note').textContent=t('有未保存的修改','You have unsaved changes');$<HTMLButtonElement>('save').disabled=false};$('save-bar').hidden=!editing;$('edit').innerHTML=icon('edit')+t(editing?'结束编辑':'编辑文字',editing?'Done editing':'Edit text');}
async function loadTrack(){if(loadingTrack)return;loadingTrack=true;try{track=await call('session.editor.read',args());renderCues();await context({...args(),title:session?.title})}finally{loadingTrack=false}}
async function preview(at=0){if(player&&at>=player.start&&at<player.end){player.media.currentTime=at-player.start;return;}const generation=++previewGeneration;const button=$<HTMLButtonElement>('preview');button.innerHTML=icon('clock')+'Preparing preview…';try{const dub=session?.kind==='dubbing';const result=await call(dub?'media.preview':'media.session_preview',{session_id:session?.session_id,start:at,duration:15,...(!dub?{language:value('track')||'source'}:{})});if(generation!==previewGeneration)return;const next=await mountPlayer($('player'),result,(seconds)=>{document.querySelectorAll<HTMLElement>('[data-cue]').forEach(row=>{const cue=(track?.cues as Cue[]|undefined)?.find(c=>String(c.id)===row.dataset.cue);row.classList.toggle('active',!!cue&&cue.start_ms/1000<=seconds&&cue.end_ms/1000>seconds)})},()=>generation===previewGeneration);if(generation===previewGeneration)player=next;}finally{if(generation===previewGeneration&&button.isConnected)button.innerHTML=icon('play')+'Load preview';}}
async function showResult(){if(!session)return;const dub=session.kind==='dubbing';
 $('result').innerHTML=`<div class="actions" style="margin-bottom:18px"><button id="preview" class="button primary">${icon('play')}${t('加载试听','Load preview')}</button>${dub?`<button id="save-audio" class="button">${icon('download')}${t('保存音频','Save audio')}</button>`:''}<button id="native-open" class="text-button">${t('在 VoxStudio 中打开','Open in VoxStudio')}${icon('external')}</button></div><div id="player" class="player-box" hidden></div>${dub?'':`<section class="card" style="margin-top:22px"><div class="toolbar"><div class="actions"><select id="track" aria-label="${t('字幕语言','Caption language')}"><option value="source">${t('原文','Original')}</option>${(session.translation_languages??[]).map((l:string)=>`<option value="${esc(l)}">${esc(languageLabel(l))}</option>`).join('')}</select><span id="cue-count" class="muted"></span></div><button id="edit" class="button small">${icon('edit')}${t('编辑文字','Edit text')}</button></div><div id="cues"><div class="skeleton wide"></div></div><div id="save-bar" class="save-bar" hidden><span id="save-note">${t('可修改文字与时间','Edit wording and timing')}</span><div class="actions"><button id="discard" class="button small">${t('放弃修改','Discard')}</button><button id="save" class="button primary small" disabled>${t('保存修改','Save changes')}</button></div></div></section><details><summary>${t('翻译与导出','Translate & export')}</summary><div class="field-grid"><div><label for="translate-language" class="eyebrow">${t('添加译文','ADD TRANSLATION')}</label><div class="export-row"><select id="translate-language">${languages()}</select><button id="translate" class="button">${t('添加','Translate')}</button></div></div><div><label for="format" class="eyebrow">${t('导出当前轨道','EXPORT THIS TRACK')}</label><div class="export-row"><select id="format"><option value="srt">SRT</option><option value="vtt">VTT</option><option value="txt">TXT</option></select><button id="export" class="button">${icon('download')}${t('导出','Export')}</button></div></div></div><p class="field-hint">${t('字幕保存在 VoxStudio；导出时可选择目标位置。','Captions stay in VoxStudio. Choose a destination when exporting.')}</p></details>`}`;
 action('preview',()=>preview());action('native-open',()=>openNativeSession(session!.session_id));
 if(dub){action('save-audio',async()=>{const r=await call('media.save_result',{session_id:session!.session_id});if(r.outcome==='saved')notice(t('音频已保存','Audio saved'))});return;}
 const select=$<HTMLSelectElement>('track');let previous='source';select.onchange=async()=>{if(dirty){select.value=previous;notice(t('先保存或放弃修改，再切换语言','Save or discard changes before switching languages.'),true);return}previous=select.value;resetPreview();$('preview').innerHTML=icon('play')+'Load preview';try{await loadTrack()}catch(e){notice(String(e),true)}};
 action('edit',async()=>{if(dirty)throw new Error(t('请先保存或放弃修改','Save or discard your changes first.'));editing=!editing;renderCues()});
 action('discard',async()=>{dirty=false;editing=false;renderCues()});
 action('save',async()=>{const ops=operations();if(ops.length){track=await call('session.editor.commit',{...args(),expected_revision:track!.revision,operations:ops,request_id:crypto.randomUUID()});notice(t('修改已保存到 VoxStudio','Changes saved in VoxStudio'))}dirty=false;editing=false;renderCues()});
 action('export',async()=>{if(dirty)throw new Error(t('导出前请先保存修改','Save your changes before exporting.'));const document=await call('documents.export',{...args(),format:value('format')});const r=await call('documents.save_as',{document_id:document.document_id});if(r.outcome==='saved')notice(t('文件已导出','File exported'))});
 action('translate',async()=>{if(dirty)throw new Error(t('翻译前请先保存修改','Save your changes before translating.'));await call('transcription.translate',{session_id:session!.session_id,target_languages:[value('translate-language')]});notice(t('译文已添加','Translation added'));await loadSession(session!.session_id)});
 try{await loadTrack()}catch(e){$('cues').innerHTML=`<div class="empty-state"><h3>${t('文字暂不可编辑','Text is not available for editing')}</h3><p>${esc(e instanceof Error?e.message:String(e))}</p></div>`;$<HTMLButtonElement>('edit').disabled=true;}
}
async function loadSession(id:string){stopJob?.();resetPreview();const snapshot=await call('media.status',{session_id:id});session={...session,...snapshot,session_id:id};$('detail').innerHTML=`<div class="detail-heading"><p class="eyebrow">${session.kind==='dubbing'?'VOICEOVER':'TRANSCRIPT'}</p><h1>${esc(session.title||t('会话详情','Session details'))}</h1><div class="detail-meta"><span id="state"></span><span>${t('内容保存在 VoxStudio','Saved in VoxStudio')}</span></div></div><div id="job" class="job-card" hidden></div><div id="result"></div>`;
 $('state').textContent=t(session.kind==='dubbing'?'配音作品':'音视频转录',session.kind==='dubbing'?'Voiceover':'Audio & video transcript');
 if(snapshot.status==='completed'){await showResult();return;}
 $('job').hidden=false;const render=(v:Obj)=>{$('job').innerHTML=progress(v);if(v.status==='completed')void loadSession(id).catch(e=>notice(String(e),true))};render(snapshot);if(!['failed','cancelled','idle'].includes(snapshot.status))stopJob=poll(()=>call('media.status',{session_id:id}),render);
}
start('voxstudio.session_panel',async data=>{if(dirty)return;if(!data.session_id){$('detail').innerHTML=`<div class="empty-state"><span class="empty-icon">${icon('text')}</span><h3>${t('打开一段会话','Open a session')}</h3><p>${t('在会话列表中选择一个转录或配音作品。','Choose a transcript or voiceover from your sessions.')}</p><button id="choose-session" class="button primary" style="margin-top:20px">${t('选择会话','Browse sessions')}${icon('arrow')}</button></div>`;action('choose-session',()=>openPanel('app_workbench'));return;}session=data;if(data.remote_only){$('detail').innerHTML=`<div class="detail-heading"><p class="eyebrow">CLOUD SESSION</p><h1>${esc(data.title)}</h1></div><div class="card"><h3>Available in VoxStudio</h3><p class="muted" style="margin-top:10px">This session is stored in the cloud. Download it in VoxStudio to preview or edit it here.</p></div>`;return;}await loadSession(data.session_id)});
